config/routes.rb
Rails.application.routes.draw do
  root to: "homes#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :decks do
    resources :cards, except: :index
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if cookies[:user_id]
      user_id = cookies.signed[:user_id]
      User.find_by_id(user_id)
    end
  end
  helper_method :current_user

  def sign_in(user)
    cookies.signed[:user_id] = user.id
  end

  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user
  end
  helper_method :signed_in?
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate

  def show
    @deck = find_deck
    @card = find_card(@deck)
  end

  def new
    @deck = find_deck
    @card = @deck.cards.new
  end

  def create
    @deck = find_deck
    @card = @deck.cards.new(card_params)
    @card.save
    redirect_to @deck
  end

  def edit
    @deck = find_deck
    @card = find_card(@deck)
  end

  def update
    @deck = find_deck
    @card = find_card(@deck)
    @card.update(card_params)
    redirect_to deck_card_path(@deck, @card)
  end

  def destroy
    @deck = find_deck
    @card = find_card(@deck)
    @card.destroy
    redirect_to @deck
  end

  private

  def find_deck
    current_user.decks.find(params[:deck_id])
  end

  def find_card(deck)
    deck.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:front, :back)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate

  def index
    @decks = current_user.decks
  end

  def show
    @deck = find_deck
    @cards = @deck.cards
  end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(deck_params)
    @deck.save
    redirect_to decks_path
  end

  def edit
    @deck = find_deck
  end

  def update
    @deck = find_deck
    @deck.update(deck_params)
    redirect_to @deck
  end

  def destroy
    @deck = find_deck
    @deck.destroy
    redirect_to decks_path
  end

  private

  def find_deck
    current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    sign_in(user)
    redirect_to decks_path
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    sign_in @user
    redirect_to decks_path
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<div>
  <%= form.label :front %>
  <%= form.text_field :front %>
</div>
<div>
  <%= form.label :back %>
  <%= form.text_field :back %>
</div>

app/views/cards/edit.html.erb
<%= form_for [@deck, @card] do |form| %>
  <%= render form %>
  <%= form.submit "Update card" %>
<% end %>

app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |form| %>
  <%= render form %>
  <%= form.submit "Create card" %>
<% end %>

app/views/cards/show.html.erb
<%= link_to @deck.name, @deck %>

<div><%= @card.front %></div>
<div><%= @card.back %></div>

<%= link_to "Edit", edit_deck_card_path(@deck, @card) %>
<%= link_to "Delete", [@deck, @card], method: :delete %>

app/views/decks/edit.html.erb
<%= form_for(@deck) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Update deck" %>
<% end %>

app/views/decks/index.html.erb
<%= link_to "New deck", new_deck_path %>

<% @decks.each do |deck| %>
  <div>
    <%= link_to deck.name, deck %>

    <%= link_to "Edit", edit_deck_path(deck) %>
    <%= link_to "Delete", deck, method: :delete %>
  </div>
<% end %>

app/views/decks/new.html.erb
<%= form_for(@deck) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Create deck" %>
<% end %>

app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>
<h2><%= @deck.name %></h2>

<% @cards.each do |card| %>
  <%= link_to card.front, [@deck, card] %>
<% end %>

<%= link_to "New card", new_deck_card_path(@deck) %>

app/views/homes/index.html.erb
Welcome to the flashcard app!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
    <% if signed_in? %>
      Welcome <%= current_user.email %>
      <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_session_path %>
      <%= link_to "Sign up", new_user_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <%= form.submit "Sign up" %>
<% end %>